# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

sudo: false

cache:
  pip: true

python:
  # - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install PyMeta3 -q
  - pip install coverage -q
  - pip install codecov -q
  - pip install flake8 -q

  - pip --version
  - flake8 --version

script:
  - flake8
  - coverage run tests.py

after_success:
  - codecov
