# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

sudo: false

cache:
  pip: true

python:
  - "2.6"
  - "2.7"

install:
  - pip install PyMeta3
  - pip install coverage
  - pip install codecov
  #- pip install flake8

script:
  - coverage run tests.py

after_success:
  - codecov
